<a href="https://colab.research.google.com/github/HoseinNekouei/RNN-Exercise/blob/main/HW1_RNN%26Transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
from tensorflow import keras
from keras import layers

In [26]:
import tensorflow as tf
import numpy as np

# an Array with shape ( 10, 8) & batch_size = 32
input = np.random.random([32, 10, 8]).astype(np.float32)
print(f'shape of input: {input.shape}')

simple_rnn = layers.SimpleRNN(4)
output = simple_rnn(input)

print(f'Shape of output: {output.shape}')

simple_rnn = layers.SimpleRNN(units= 4, return_state = True, return_sequences = True)
whole_sequences_output, final_state = simple_rnn(input)

print(f'whole of sequences output:\n {whole_sequences_output[0]}, shape: {whole_sequences_output.shape}')
print(f'final state:\n {final_state[0]} , shape: {final_state.shape}')



shape of input: (32, 10, 8)
Shape of output: (32, 4)
whole of sequences output:
 [[ 0.20121795  0.48158416 -0.5696055   0.62844265]
 [ 0.7469406  -0.15673731 -0.07065518 -0.06212314]
 [ 0.33502594 -0.2057783  -0.7009058   0.61650634]
 [-0.02587533 -0.47362676 -0.1313477   0.528511  ]
 [ 0.21875495 -0.27294648 -0.89429855  0.8202728 ]
 [ 0.7074008  -0.6750392  -0.79891515  0.68209267]
 [ 0.3255795  -0.69610566  0.17219375  0.594785  ]
 [ 0.22818927 -0.25414774 -0.7757275   0.41327804]
 [ 0.20799191 -0.7068724  -0.46881765 -0.07271965]
 [-0.25008193 -0.22527519 -0.47480693  0.6299073 ]], shape: (32, 10, 4)
final state:
 [-0.25008193 -0.22527519 -0.47480693  0.6299073 ] , shape: (32, 4)
